### PR TITLE
[DROOLS-4085] Add inheritance goal 

### PR DESCRIPTION
**Pull request by gitgabrio**
@mareknovotny @Rikkola @yesamer @ederign 

See https://issues.jboss.org/browse/DROOLS-4058

This PR add the "inheritance" goal.

### CODE REVIEW

**Review by Rikkola — APPROVED** [review]
Looks good. Do we need to unit test these bits?

**Comment by gitgabrio** [comment]
@Rikkola 

> Looks good. Do we need to unit test these bits?
I'm planning to write full tests (also integration ones) but it take too much time right now and I have other things to close, so I would like to merge it as it is.

**Review by mareknovotny — APPROVED** [review]
Disclaimer: I am not expert on GWT, so formally I am ok with the changes.

**Review by yesamer — APPROVED** [review]
Fine for me

**Comment by gitgabrio** [comment]
@ederign 
Hi! Do you have time to review this? If not, I think I'll merge it as it is. Thanks!

**Review by ederign — APPROVED** [review]

**Comment by ederign** [comment]
sorry for the delay!

**Comment by gitgabrio** [comment]
@ederign 
> sorry for the delay!
No prblm - I know you are busy with other stuff :)

**Comment by gitgabrio** [comment]
@mareknovotny @mbiarnes It seems new version (1.2) has not been published top maven central: do you know who should I ask to deploy it?

**Comment by mareknovotny** [comment]
@gitgabrio  how did you tag and release 1.2 version?

**Comment by gitgabrio** [comment]
> @gitgabrio how did you tag and release 1.2 version?

@mareknovotny @mbiarnes 
I did not anything special, just merged the branch on master. What I have to do to have the new version published ?

**Comment by mareknovotny** [comment]
@gitgabrio well, I think nothing happens automatically, so think about proper release process and do it ;) we can help you with guidance.

**Comment by gitgabrio** [comment]
> @gitgabrio well, I think nothing happens automatically, so think about proper release process and do it ;) we can help you with guidance.

@mareknovotny 
OK, thanks. Could you please provide a step-by-step guide? I've already published some plugin by myself, but surely the process for RH ones is different and I have not do that before. Thanks again!

**Comment by mareknovotny** [comment]
Here they are https://developer.jboss.org/wiki/MavenDeployingARelease, contact us on a messaging systems if you need some more help

**Pull request merged**
